DROP TABLE IF EXISTS members;

CREATE TABLE `members` (
  `MembersId` int(20) unsigned NOT NULL AUTO_INCREMENT,
  `MemberType` text,
  `FirmName` text CHARACTER SET utf8,
  `GroupsId` int(20) unsigned DEFAULT NULL,
  `GroupName` text CHARACTER SET utf8,
  `SubGroupId` int(7) DEFAULT NULL,
  `SubGroupName` text,
  `Email` text,
  `STDCode` text,
  `Landline` text,
  `Mobile` text,
  `Shop` text CHARACTER SET utf8,
  `Complex` text CHARACTER SET utf8,
  `Street` text CHARACTER SET utf8,
  `SectorMohalla` varchar(255) DEFAULT NULL,
  `AreaId` int(20) unsigned DEFAULT NULL,
  `AreaName` text CHARACTER SET utf8,
  `CityId` int(20) unsigned DEFAULT NULL,
  `CityName` text CHARACTER SET utf8,
  `DistrictId` int(20) unsigned DEFAULT NULL,
  `DistrictName` text CHARACTER SET utf8,
  `PIN` text,
  `GSTN` varchar(50) DEFAULT NULL,
  `RegistrationNo` text,
  `RegistrationNoOld` text,
  `Approved` tinyint(1) DEFAULT NULL,
  `CertificatePrint` tinyint(1) DEFAULT NULL,
  `CertModeOfDispatch` text CHARACTER SET utf8,
  `CertDetails` text CHARACTER SET utf8,
  `CertUserId` int(20) unsigned DEFAULT NULL,
  `Representative1` text CHARACTER SET utf8,
  `ImageRep1` text,
  `MobileRep1` text,
  `MobileRep1Alternate` varchar(20) DEFAULT NULL,
  `OrgDesignationRep1` text CHARACTER SET utf8,
  `EmailRep1` text,
  `SalutationRep1` text,
  `GoverningBodyIdRep1` int(20) unsigned DEFAULT NULL,
  `GoverningBodyIdNameRep1` text CHARACTER SET utf8,
  `GBDesignationIdRep1` int(20) unsigned DEFAULT NULL,
  `GBDesignationIdNameRep1` text CHARACTER SET utf8,
  `CommitteeIDRep1` int(20) unsigned DEFAULT NULL,
  `CommitteeIDNameRep1` text CHARACTER SET utf8,
  `CdesignationIdRep1` int(20) unsigned DEFAULT NULL,
  `CdesignationIdNameRep1` text CHARACTER SET utf8,
  `CardPrintRep1` text,
  `CardDispatchModeRep1` text CHARACTER SET utf8,
  `CardDetailsRep1` text CHARACTER SET utf8,
  `CardUserIdRep1` int(20) unsigned DEFAULT NULL,
  `Representative2` text CHARACTER SET utf8,
  `ImageRep2` text,
  `MobileRep2` text,
  `MobileRep2Alternate` varchar(20) DEFAULT NULL,
  `OrgDesignationRep2` text CHARACTER SET utf8,
  `EmailRep2` text,
  `SalutationRep2` text,
  `GoverningBodyIdRep2` int(20) unsigned DEFAULT NULL,
  `GoverningBodyIdNameRep2` text CHARACTER SET utf8,
  `GBDesignationIdRep2` int(20) unsigned DEFAULT NULL,
  `GBDesignationIdNameRep2` text CHARACTER SET utf8,
  `CommitteeIDRep2` int(20) unsigned DEFAULT NULL,
  `CommitteeIDNameRep2` text CHARACTER SET utf8,
  `CdesignationIdRep2` int(20) unsigned DEFAULT NULL,
  `CdesignationIdNameRep2` text CHARACTER SET utf8,
  `CardPrintRep2` text,
  `CardDispatchModeRep2` text CHARACTER SET utf8,
  `CardDetailsRep2` text CHARACTER SET utf8,
  `CardUserIdRep2` int(20) unsigned DEFAULT NULL,
  `CreatedBy` int(20) DEFAULT NULL,
  `UpdateBy` int(20) DEFAULT NULL,
  `CreationDate` datetime DEFAULT NULL,
  `UpdationDate` datetime DEFAULT NULL,
  `DeletedStatus` tinyint(1) DEFAULT NULL,
  `GBOrderRep1` int(20) unsigned DEFAULT NULL,
  `GBOrderRep2` int(20) unsigned DEFAULT NULL,
  `COrderRep1` int(20) unsigned DEFAULT NULL,
  `COrderRep2` int(20) unsigned DEFAULT NULL,
  `MemDoc` text,
  `DocTitle` text CHARACTER SET utf8,
  `Remark` text CHARACTER SET utf8,
  `FY` varchar(150) DEFAULT NULL,
  `old_remarks` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`MembersId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




